-- 코드를 입력하세요
-- SELECT A.*
-- FROM MEMBER_PROFILE A, (
--     SELECT COUNT(*) CNT, 
--     MEMBER_ID FROM REST_REVIEW
--     ORDER BY CNT DESC
--     )
--     B
-- WHERE A.MEMBER_ID = B.MEMBER_ID

-- SELECT  COUNT(MEMBER_ID) AS CNT,MEMBER_ID
-- FROM REST_REVIEW
-- GROUP BY MEMBER_ID
-- ORDER BY CNT DESC

SELECT A.MEMBER_NAME,B.REVIEW_TEXT,TO_CHAR(B.REVIEW_DATE,'YYYY-MM-DD') REVIEW_DATE 
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
AND A.MEMBER_ID IN (SELECT MEMBER_ID
                        FROM REST_REVIEW
                        GROUP BY MEMBER_ID
                        HAVING COUNT(*) = 
                      (SELECT MAX(COUNT(*))
                         FROM REST_REVIEW
                         GROUP BY MEMBER_ID)) 



ORDER BY REVIEW_DATE, REVIEW_TEXT