-- -- 코드를 입력하세요

SELECT X.AUTHOR_ID, Y.AUTHOR_NAME,  X.CATEGORY ,SUM(TOTAL_SALES)
FROM  (
        SELECT A.AUTHOR_ID, A.CATEGORY, A.PRICE * B.SALES AS TOTAL_SALES
        FROM BOOK A, 
            (
            SELECT BOOK_ID, SUM(SALES) AS SALES
            FROM BOOK_SALES
            WHERE TO_CHAR(SALES_DATE , 'YYYYMM') = '202201'
            GROUP BY BOOK_ID
            ) B 
        WHERE A.BOOK_ID = B.BOOK_ID
        )
        X,
        AUTHOR Y
WHERE X.AUTHOR_ID = Y.AUTHOR_ID
GROUP BY X.AUTHOR_ID, X.CATEGORY,Y.AUTHOR_NAME
ORDER BY AUTHOR_ID, CATEGORY DESC